config/routes.rb
Micomunidad::Application.routes.draw do
  
 get "logout" => "sessions#destroy", :as => "logout"
 get "login" => "sessions#new", :as => "login"
 get "signup" => "users#new", :as => "signup"
 resources :users
 resources :sessions
 resources :groups

  root :to => "users#index"

  resources :galerias
  resources :fotos

end

app/models/foto.rb
class Foto < ActiveRecord::Base
  attr_accessible :galeria_id, :image, :titulo, :remote_image_url
  mount_uploader :image, ImageUploader
  belongs_to :galeria

  def to_jq_upload
    {
      "name" => read_attribute(:image),
      "size" => image.size,
      "url" => image.url,
      "thumbnail_url" => image.thumb.url,
      "delete_type" => "DELETE"
    }
  end
end

app/models/galeria.rb
class Galeria < ActiveRecord::Base
  attr_accessible :titulo
  has_many :fotos
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  has_many :memberships
  has_many :users, :through => :memberships
  validates_presence_of :name
  

  
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :groups
  belongs_to :users
  attr_accessible :user_id, :group_id
end

app/models/user.rb
class User < ActiveRecord::Base
 authenticates_with_sorcery!
  before_save :lowercase_email
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  has_many :memberships
  has_many :groups, :through => :memberships

  def lowercase_email
  	self.email = self.email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
 before_filter :require_login

  def new
    @foto = Foto.new(:galeria_id => params[:galeria_id])
  end


  def create
    @foto = Foto.new(params[:foto])
    @foto.save
    if @foto.save
      flash[:notice] = "Foto Creada."
      respond_to do |format|
        format.html {                                         #(html response is for browsers using iframe sollution)
          render :json => [@foto.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@foto.to_jq_upload].to_json
        }
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @foto = Foto.find(params[:id])
  end

  def show
  end
  def update
    @foto = Foto.find(params[:id])
    if @foto.update_attributes(params[:foto])
      flash[:notice] = "Foto actualizada."
      redirect_to @foto.galeria
    else
      render :action => 'edit'
    end
  end
  def destroy
    @foto = Foto.find(params[:id])
    @foto.destroy
    flash[:notice] = "Foto Borrada."
    redirect_to @foto.galeria
  end

end

app/controllers/galerias_controller.rb
class GaleriasController < ApplicationController
  before_filter :require_login
  def index
    @galerias = Galeria.all
  end

  def new
    @galeria = Galeria.new
  end


  def create
    @galeria = Galeria.new(params[:galeria])
    if @galeria.save
      flash[:notice] = "Galeria Creada."
      redirect_to @galeria
    else
      render :action => 'new'
    end
  end

  def edit
    @galeria = Galeria.find(params[:id])
  end


   def show
    @galeria = Galeria.find(params[:id])
  end

  def destroy
    @galeria = Galeria.find(params[:id])
    @galeria.destroy
    flash[:notice] = "Galeria borrada."
    redirect_to galerias_url
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])    
    respond_to do |format|
      format.html
    end
  end

  def new
    @group = Group.new

  end

  def create 
    @group = Group.new(params[:group]) 
    @group.memberships.build(:user_id => current_user.id)
    logger.info @group.users

    @group.users.each do |x|
      @group.memberships.build(:user_id => x.id )
    end

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Success!') }
      else
        format.html { render :action => "new" }
      end
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = login(params[:email].downcase, params[:password], params[:remember_me])
  if user
    redirect_back_or_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Email or password was invalid"
    render :new
  end
end

def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @group = Group.find(1)
    @user = User.new(params[:user])
    @user.email = @user.email.downcase
    if @user.save
      @membership.user
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foto_helper.rb
module FotoHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fotos/_form.html.erb
<%= form_for @foto, :html => {:multipart => true, :id => "fileupload"  } do |f| %>
  <%= f.hidden_field :galeria_id %>
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span><%= t('fileupload.add_files') %></span>
                    <%= f.file_field :image  %>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span><%= t('fileupload.start_upload') %></span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span><%= t('fileupload.cancel_upload') %></span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span><%= t('fileupload.delete_multi') %></span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active fade">
                    <div class="bar" style="width:0%;"></div>
                </div>
            </div>
        </div>
        <div class="fileupload-loading"></div>
          <br>
          <!-- The table listing the files available for upload/download -->
          <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
        </table>
<% end %>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<%= render "shared/fileupload/queue" %>

<%= render "shared/fileupload/index" %>

<%= render "shared/fileupload/js_include_local" %>

app/views/fotos/_s3form.html.erb
<%= s3_uploader_form as: "model[image_url]", id: "image_uploader" do %>
  <%= file_field_tag :file, multiple: true %>
<% end %>

app/views/fotos/edit.html.erb
<%= render 'form' %>

<p><%= link_to "Volver a la galeria", @foto.galeria %></p>

app/views/fotos/new.html.erb
<%= render 'form' %>

<p><%= link_to "Volver a la galeria", @foto.galeria %></p>

app/views/galerias/_form.html.erb
<div>
<%= form_for @galeria do |f| %>
  
  <p>
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </p>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/galerias/edit.html.erb
<h1>Galeria#edit</h1>
<p>Find me in app/views/galeria/edit.html.erb</p>

app/views/galerias/index.html.erb
<h><%= "Galerias" %></h>

<% for galeria in @galerias %>
  <div class="galeria">
    <h2><%= link_to galeria.titulo, galeria %></h2>
    Fotos: <%= galeria.fotos.size %>
  </div>
<% end %>

<p><%= link_to "Nueva Galeria", new_galeria_path %></p>

app/views/galerias/new.html.erb
<%="Nueva Galeria" %>

<%= render 'form' %>

<p><%= link_to "Volver al listado", galerias_path %></p>

app/views/galerias/show.html.erb
<div id="modal-gallery" class="modal modal-gallery hide fade" tabindex="-1">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn btn-primary modal-next">Next <i class="icon-arrow-right icon-white"></i></a>
        <a class="btn btn-info modal-prev"><i class="icon-arrow-left icon-white"></i> Previous</a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000"><i class="icon-play icon-white"></i> Slideshow</a>
        <a class="btn modal-download" target="_blank"><i class="icon-download"></i> Download</a>
    </div>
</div>
<div id="gallery" data-toggle="modal-gallery" data-target="#modal-gallery">
<% for foto in @galeria.fotos %>
  <a href= <%= foto.image_url()  %> rel="gallery">
    <img src= <%= foto.image_url(:thumb)  %> class="img-polaroid" />
  </a>
   
<% end %>
  
</div>
<p>
  <ul class="nav nav-pills">
 
  <%= link_to "Añadir foto", new_foto_path(:galeria_id => @galeria), class: "btn btn-primary" %> |
  <%= link_to "Borrar Galeria", @galeria, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Ver Galerias", galerias_path %>
</ul>
</p>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
  <% if @group.errors.any? %>
    <div class="error_messages2">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @group.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- fpalen -->
  <div class="field">
    
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/groups/show.html.erb
<% for foto in @galeria.fotos %>
  <a href= <%= foto.image_url()  %> rel="gallery">
    <img src= <%= foto.image_url(:thumb)  %> class="img-polaroid-javisu" />
  </a>
   
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galeria Snoopy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag 'http://blueimp.github.com/cdn/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag '/javascripts/jquery-file-upload/css/style.css' %>
  <%= stylesheet_link_tag "http://blueimp.github.com/cdn/css/bootstrap-responsive.min.css" %>
  <%= stylesheet_link_tag "http://blueimp.github.com/cdn/css/bootstrap-ie6.min.css" %>
  <%= stylesheet_link_tag "http://blueimp.github.com/Bootstrap-Image-Gallery/css/bootstrap-image-gallery.min.css" %>
  <%= stylesheet_link_tag "/javascripts/jquery-file-upload/css/jquery.fileupload-ui.css" %>
  <%= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js" %>

  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js' %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js' %>


  <%= javascript_include_tag 'http://blueimp.github.com/JavaScript-Templates/tmpl.min.js' %>
  <%= javascript_include_tag 'http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js' %>

  <%= javascript_include_tag '/javascripts/jquery-file-upload/js/jquery.iframe-transport.js' %>
  <%= javascript_include_tag '/javascripts/jquery-file-upload/js/jquery.fileupload.js' %>
  <%= javascript_include_tag '/javascripts/jquery-file-upload/js/jquery.fileupload-ui.js' %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<script src="http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js">

@import "bootstrap/image-gallery";
@import "bootstrap"
</script>

<body>
	<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Galeria Snoopy</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Crear Grupo", new_group_path %></li>
          <li><%= link_to "Galerias", galerias_path %></li>
          <% if current_user %>
            <li> Hola <%= current_user.email %> </li>
            <li> <%= link_to "Log out", logout_path %> </li>
          <% else %>
            <li> <%= link_to "Sign up", signup_path %> </li>
             <a class="btn btn-primary" data-toggle="modal" href="#myModal" >Login</a> 
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="modal hide" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">x</button>
    <h3>Login to MyWebsite.com</h3>
  </div>
  <div class="modal-body">
    <%= form_tag sessions_path do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
    <%= label_tag :remember_me %>
  </div>
    <%= submit_tag "Entrar", :class => "btn btn-primary" %>
<% end %>
    
  </div>
  <div class="modal-footer">
    New To MyWebsite.com?
    <a href="#" class="btn btn-primary">Register</a>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
    <div class="span3">
      <h2>About Us</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
    </div>
  </div>
</div>

</body>
</html>

app/views/shared/_fileupload.html.erb
<%= form_for @object_new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span><%= t('fileupload.add_files') %></span>
                    <%= f.file_field :path %>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span><%= t('fileupload.start_upload') %></span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span><%= t('fileupload.cancel_upload') %></span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span><%= t('fileupload.delete_multi') %></span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active fade">
                    <div class="bar" style="width:0%;"></div>
                </div>
            </div>
        </div>
        <!-- The loading indicator is shown during image processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
        </table>
    <% end %>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<%= render "shared/fileupload/queue" %>

<%= render "shared/fileupload/index" %>

<%= render "shared/fileupload/js_include_local" %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>